-- ============================================
-- SQL Migration: Complete Schema Initialization (Clean Slate & Fix Recursion)
-- LesMap Samarinda
-- ============================================

-- WARNING: This script will drop existing tables to ensure a clean and correct schema.
-- This is necessary to fix type mismatches and RLS infinite recursion errors.

-- 1. Drop existing views and tables in correct order (due to foreign keys)
DROP VIEW IF EXISTS public.dashboard_stats CASCADE;
DROP TABLE IF EXISTS public.reviews CASCADE;
DROP TABLE IF EXISTS public.course_fasilitas CASCADE;
DROP TABLE IF EXISTS public.course_places CASCADE;
DROP TABLE IF EXISTS public.fasilitas CASCADE;
DROP TABLE IF EXISTS public.categories CASCADE;
DROP TABLE IF EXISTS public.users CASCADE;

-- 2. Create Roles (if they do not exist)
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'user_role') THEN
        CREATE ROLE user_role;
    END IF;
EXCEPTION WHEN OTHERS THEN
    RAISE NOTICE 'Role user_role creation skipped: %', SQLERRM;
END $$;

DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'admin_role') THEN
        CREATE ROLE admin_role;
    END IF;
EXCEPTION WHEN OTHERS THEN
    RAISE NOTICE 'Role admin_role creation skipped: %', SQLERRM;
END $$;

-- 3. Create public.users table (id is UUID, matching auth.users)
CREATE TABLE public.users (
    id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
    email TEXT NOT NULL,
    full_name TEXT,
    phone TEXT,
    role TEXT NOT NULL DEFAULT 'user' CHECK (role IN ('user', 'admin')),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ
);

-- 4. Create categories table
CREATE TABLE public.categories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    icon TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- 5. Create fasilitas table
CREATE TABLE public.fasilitas (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    icon TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- 6. Create course_places table (owner_id MUST be UUID to match public.users.id)
CREATE TABLE public.course_places (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    address TEXT NOT NULL,
    district TEXT NOT NULL,
    city TEXT NOT NULL DEFAULT 'Samarinda',
    province TEXT NOT NULL DEFAULT 'Kalimantan Timur',
    category TEXT NOT NULL,
    description TEXT,
    phone TEXT,
    whatsapp TEXT,
    email TEXT,
    website TEXT,
    instagram TEXT,
    latitude DOUBLE PRECISION NOT NULL,
    longitude DOUBLE PRECISION NOT NULL,
    price_min NUMERIC,
    price_max NUMERIC,
    status TEXT NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'approved', 'rejected')),
    owner_id UUID REFERENCES public.users(id) ON DELETE CASCADE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ
);

-- 7. Create course_fasilitas table (junction table)
CREATE TABLE public.course_fasilitas (
    course_id BIGINT REFERENCES public.course_places(id) ON DELETE CASCADE,
    fasilitas_id BIGINT REFERENCES public.fasilitas(id) ON DELETE CASCADE,
    PRIMARY KEY (course_id, fasilitas_id)
);

-- 8. Create reviews table (user_id MUST be UUID to match public.users.id)
CREATE TABLE public.reviews (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    course_id BIGINT REFERENCES public.course_places(id) ON DELETE CASCADE,
    user_id UUID REFERENCES public.users(id) ON DELETE CASCADE,
    rating INTEGER NOT NULL CHECK (rating >= 1 AND rating <= 5),
    comment TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- 9. Create trigger for new users
DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
DROP FUNCTION IF EXISTS handle_new_user();

CREATE OR REPLACE FUNCTION handle_new_user()
RETURNS TRIGGER AS $$
BEGIN
    -- Insert into public.users with role from metadata (defaults to 'user')
    INSERT INTO public.users (id, email, full_name, phone, role, created_at)
    VALUES (
        NEW.id,
        NEW.email,
        COALESCE(NEW.raw_user_meta_data->>'full_name', NEW.email),
        NEW.raw_user_meta_data->>'phone',
        COALESCE(NEW.raw_user_meta_data->>'role', 'user'),
        NOW()
    );
    RETURN NEW;
EXCEPTION WHEN OTHERS THEN
    -- If user already exists, just return new
    RAISE NOTICE 'User profile may already exist: %', SQLERRM;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Create trigger on auth.users
CREATE TRIGGER on_auth_user_created
    AFTER INSERT ON auth.users
    FOR EACH ROW EXECUTE FUNCTION handle_new_user();

-- ============================================
-- 10. Create Helper Functions (SECURITY DEFINER to bypass RLS and prevent infinite recursion)
-- ============================================

-- Helper function to check if user is admin (runs as owner, bypassing RLS recursion)
CREATE OR REPLACE FUNCTION public.is_admin(user_id UUID)
RETURNS BOOLEAN AS $$
BEGIN
    RETURN EXISTS (
        SELECT 1 FROM public.users
        WHERE id = user_id AND role = 'admin'
    );
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Helper function to promote user to admin
CREATE OR REPLACE FUNCTION public.make_admin(user_id UUID)
RETURNS VOID AS $$
BEGIN
    UPDATE public.users SET role = 'admin' WHERE id = user_id;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Helper function to check if user owns any course places
CREATE OR REPLACE FUNCTION public.is_owner(user_id UUID)
RETURNS BOOLEAN AS $$
BEGIN
    RETURN EXISTS (
        SELECT 1 FROM public.course_places
        WHERE owner_id = user_id
        LIMIT 1
    );
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- ============================================
-- 11. Enable Row Level Security (RLS)
-- ============================================
ALTER TABLE public.users ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.categories ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.fasilitas ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.course_places ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.course_fasilitas ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.reviews ENABLE ROW LEVEL SECURITY;

-- ============================================
-- 12. Create RLS Policies (using public.is_admin() to prevent recursion)
-- ============================================
DROP POLICY IF EXISTS "Users can view own profile" ON public.users;
DROP POLICY IF EXISTS "Users can update own profile" ON public.users;
DROP POLICY IF EXISTS "Admins can view all users" ON public.users;
DROP POLICY IF EXISTS "Admins can update all users" ON public.users;
DROP POLICY IF EXISTS "Public can view approved course places" ON public.course_places;
DROP POLICY IF EXISTS "Authenticated users can insert course places" ON public.course_places;
DROP POLICY IF EXISTS "Users can view own places" ON public.course_places;
DROP POLICY IF EXISTS "Users can update own places" ON public.course_places;
DROP POLICY IF EXISTS "Admins can manage all course places" ON public.course_places;
DROP POLICY IF EXISTS "Public can view categories" ON public.categories;
DROP POLICY IF EXISTS "Admins can manage categories" ON public.categories;
DROP POLICY IF EXISTS "Public can view fasilitas" ON public.fasilitas;
DROP POLICY IF EXISTS "Admins can manage fasilitas" ON public.fasilitas;
DROP POLICY IF EXISTS "Public can view reviews for approved places" ON public.reviews;
DROP POLICY IF EXISTS "Authenticated users can insert reviews" ON public.reviews;
DROP POLICY IF EXISTS "Users can view own reviews" ON public.reviews;
DROP POLICY IF EXISTS "Admins can manage all reviews" ON public.reviews;

-- Users table policies (no recursion thanks to public.is_admin() SECURITY DEFINER)
CREATE POLICY "Users can view own profile" ON public.users
    FOR SELECT USING (auth.uid() = id);

CREATE POLICY "Users can update own profile" ON public.users
    FOR UPDATE USING (auth.uid() = id);

CREATE POLICY "Admins can view all users" ON public.users
    FOR SELECT USING ( public.is_admin(auth.uid()) );

CREATE POLICY "Admins can update all users" ON public.users
    FOR UPDATE USING ( public.is_admin(auth.uid()) );

-- Course places policies
CREATE POLICY "Public can view approved course places" ON public.course_places
    FOR SELECT USING (status = 'approved');

CREATE POLICY "Authenticated users can insert course places" ON public.course_places
    FOR INSERT WITH CHECK (auth.uid() IS NOT NULL AND owner_id = auth.uid());

CREATE POLICY "Users can view own places" ON public.course_places
    FOR SELECT USING (
        owner_id = auth.uid() OR
        public.is_admin(auth.uid())
    );

CREATE POLICY "Users can update own places" ON public.course_places
    FOR UPDATE USING (
        owner_id = auth.uid() OR
        public.is_admin(auth.uid())
    );

CREATE POLICY "Admins can manage all course places" ON public.course_places
    FOR ALL USING ( public.is_admin(auth.uid()) );

-- Categories policies
CREATE POLICY "Public can view categories" ON public.categories
    FOR SELECT USING (true);

CREATE POLICY "Admins can manage categories" ON public.categories
    FOR ALL USING ( public.is_admin(auth.uid()) );

-- Fasilitas policies
CREATE POLICY "Public can view fasilitas" ON public.fasilitas
    FOR SELECT USING (true);

CREATE POLICY "Admins can manage fasilitas" ON public.fasilitas
    FOR ALL USING ( public.is_admin(auth.uid()) );

-- Course Fasilitas policies
DROP POLICY IF EXISTS "Public can view course fasilitas" ON public.course_fasilitas;
DROP POLICY IF EXISTS "Admins can manage course fasilitas" ON public.course_fasilitas;
CREATE POLICY "Public can view course fasilitas" ON public.course_fasilitas FOR SELECT USING (true);
CREATE POLICY "Admins can manage course fasilitas" ON public.course_fasilitas FOR ALL USING (
    public.is_admin(auth.uid())
);

-- Reviews policies
CREATE POLICY "Public can view reviews for approved places" ON public.reviews
    FOR SELECT USING (
        EXISTS (SELECT 1 FROM public.course_places WHERE id = course_id AND status = 'approved')
    );

CREATE POLICY "Authenticated users can insert reviews" ON public.reviews
    FOR INSERT WITH CHECK (auth.uid() IS NOT NULL AND user_id = auth.uid());

CREATE POLICY "Users can view own reviews" ON public.reviews
    FOR SELECT USING (
        user_id = auth.uid() OR
        public.is_admin(auth.uid())
    );

CREATE POLICY "Admins can manage all reviews" ON public.reviews
    FOR ALL USING ( public.is_admin(auth.uid()) );

-- ============================================
-- 13. Grant permissions to roles
-- ============================================
GRANT USAGE ON SCHEMA public TO authenticated;
GRANT USAGE ON SCHEMA public TO anon;

GRANT SELECT ON public.users TO authenticated;
GRANT SELECT ON public.course_places TO authenticated;
GRANT SELECT ON public.categories TO authenticated;
GRANT SELECT ON public.fasilitas TO authenticated;
GRANT SELECT ON public.course_fasilitas TO authenticated;
GRANT SELECT ON public.reviews TO authenticated;

GRANT INSERT, UPDATE ON public.users TO authenticated;
GRANT INSERT ON public.course_places TO authenticated;
GRANT INSERT ON public.reviews TO authenticated;

GRANT SELECT ON public.course_places TO anon;
GRANT SELECT ON public.categories TO anon;
GRANT SELECT ON public.fasilitas TO anon;
GRANT SELECT ON public.course_fasilitas TO anon;
GRANT SELECT ON public.reviews TO anon;

-- ============================================
-- 14. Create Helper View for Dashboard Stats
-- ============================================
DROP VIEW IF EXISTS public.dashboard_stats;
CREATE OR REPLACE VIEW public.dashboard_stats AS
SELECT
    (SELECT COUNT(*) FROM public.course_places) AS total_places,
    (SELECT COUNT(*) FROM public.course_places WHERE status = 'pending') AS pending_places,
    (SELECT COUNT(*) FROM public.course_places WHERE status = 'approved') AS approved_places,
    (SELECT COUNT(*) FROM public.course_places WHERE status = 'rejected') AS rejected_places,
    (SELECT COUNT(*) FROM public.users WHERE role = 'user') AS total_users,
    (SELECT COUNT(*) FROM public.users WHERE role = 'admin') AS total_admins,
    (SELECT COUNT(*) FROM public.categories) AS total_categories,
    (SELECT COUNT(*) FROM public.fasilitas) AS total_fasilitas,
    (SELECT COUNT(*) FROM public.reviews) AS total_reviews;

GRANT SELECT ON public.dashboard_stats TO authenticated;
GRANT SELECT ON public.dashboard_stats TO anon;

-- ============================================
-- 15. Seed initial categories and facilities
-- ============================================
INSERT INTO public.categories (name, icon)
VALUES 
    ('Akademik / Bimbel', 'book-open'),
    ('Bahasa Asing', 'languages'),
    ('Musik & Seni', 'music'),
    ('Olahraga', 'activity'),
    ('Teknologi & Coding', 'code')
ON CONFLICT DO NOTHING;

INSERT INTO public.fasilitas (name, icon)
VALUES 
    ('AC / Ruangan Nyaman', 'wind'),
    ('Wifi Gratis', 'wifi'),
    ('Modul / Buku Panduan', 'book'),
    ('Sertifikat Resmi', 'award'),
    ('Parkir Luas', 'car')
ON CONFLICT DO NOTHING;
